### ISSUE TITLE
Meetings have tracking statuses (new, pending, logged, etc)

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/tutorbook#165]
Meetings have tracking statuses (new, pending, logged, approved, etc):

- [ ] CRON job (every 15 mins) that updates status on meetings from past 24 hrs (from CREATED to PENDING)
- [ ] Meetings API verifies meeting status changes (e.g. ensuring past meetings have PENDING)
- [ ] Update meeting statuses client-side as time goes on
- [ ] Update meeting status when venue link clicked (or email opened)
