### ISSUE TITLE
Add support for recurring meetings

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/tutorbook#166]
- [x] Set "recur" in calendar dialogs (using `Select`)
- [x] Show recur rules exceptions in selector
- [x] Allow for empty `rrule` selection
